#!/bin/bash
# This script takes zero or more numeric parameters, and prints the sum of the values
# for example, 'bash problem4 1 2 3' returns 6.
if [ $# -eq 0 ]; then
    echo 0
fi
echo ${*} | tr " " + | bc
